- name: Install Bigtop repository
  hosts: all
  become: yes
  tasks:
  - name: Add bigtop repository
    yum_repository:
      name: bigtop
      description: Apache Bigtop repository
      baseurl: http://repos.bigtop.apache.org/releases/1.4.0/centos/7/$basearch
      gpgkey: https://dist.apache.org/repos/dist/release/bigtop/KEYS
