Vagrant.configure(2) do |config|
	config.vm.box = 'centos/7'
	config.vm.hostname = 'bigtop.griddynamics.net'
	config.vm.network :private_network, ip: '192.168.168.17'
	config.vm.provision :ansible do |ansible|
		ansible.playbook = 'bigtop.yml'
	end
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
