- name: Install nomad
  hosts: all
  become: yes
  vars:
    nomadDir: /opt/nomad
  tasks:
  - name: Install required packages
    yum:
      name: unzip

  - name: Make directory
    file:
      name: "{{ nomadDir }}"
      state: directory

  - name: Download nomad
    unarchive:
      dest: "{{ nomadDir }}"
      remote_src: yes
      src: https://releases.hashicorp.com/nomad/0.7.1/nomad_0.7.1_linux_amd64.zip
