Vagrant.configure(2) do |config|
	config.vm.box = 'centos/7'
  (1..4).each do |num|
    config.vm.define "nomad#{num}" do |host|
    	host.vm.hostname = "nomad-#{num}.griddynamics.net"
    	host.vm.network :private_network, ip: "192.168.168.1#{num}"
    	host.vm.provision :ansible do |ansible|
    		ansible.playbook = "#{num > 2 ? 'client' : 'server'}.yml"
        ansible.raw_arguments = ['-v']
    	end
    end
  end
end
