Vagrant.configure(2) do |config|
  config.vm.box = 'centos/7'
  config.vm.hostname = 'jwt.griddynamics.net'
  config.vm.network :private_network, ip: '192.168.168.17'
  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'jwt.yml'
    ansible.raw_arguments = ['-v']
  end
end
