Vagrant.configure(2) do |config|
  config.vm.box = 'centos/7'
  (1..3).each do |num|
    host_name = "patroni-#{num}"
    config.vm.define host_name do |host|
      host.vm.hostname = "#{host_name}.griddynamics.net"
      host.vm.network :private_network, ip: "192.168.168.1#{num}"
      if num == 3
        host.vm.provision :ansible do |ansible|
          ansible.groups = {
            'haproxy' =>  ['patroni-3'],
            'postgres' => ['patroni-1', 'patroni-2'],
            'zookeeper'=> ['patroni-1', 'patroni-2', 'patroni-3']
          }
          ansible.limit = 'all'
          ansible.playbook = 'install.yml'
          ansible.raw_arguments = ['-v']
        end
      end
    end
  end
end
