Vagrant.configure(2) do |config|
  config.vm.box = 'centos/7'
  config.vm.define 'nfs-server' do |host|
    host.vm.hostname = 'nfs-server.griddynamics.net'
    host.vm.network :private_network, ip: '192.168.168.20'
    host.vm.provision :ansible do |ansible|
      ansible.limit = 'nfs-server'
      ansible.playbook = 'nfs-server.yml'
      ansible.raw_arguments = ['-v']
    end
  end
  (1..2).each do |num|
    host_name = "nfs-client-#{num}"
    config.vm.define host_name do |host|
      host.vm.hostname = "#{host_name}.griddynamics.net"
      host.vm.network :private_network, ip: "192.168.168.2#{num}"
      if num == 2
        host.vm.provision :ansible do |ansible|
          ansible.limit = 'nfs-client-*'
          ansible.playbook = 'nfs-client.yml'
          ansible.raw_arguments = ['-v']
        end
      end
    end
  end
end
