- name: Install httpd with mod_authnz_jwt
  hosts: all
  become: yes
  vars_files:
  - jwt_vars.yml
  tasks:
  - name: Install prerequisites
    yum:
      name:
      - check
      - gcc
      - gcc-c++
      - httpd
      - httpd-devel
      - jansson-devel
      - libtool
      - make
      - net-tools
      - openssl-devel
      - pkgconfig
      - zlib-devel

  - name: Download and unpack sources
    unarchive:
      src: "{{ item }}"
      dest: "{{ build_dir }}"
      remote_src: yes
    with_items:
    - "{{ libjwt_url }}"
    - "{{ mod_authnz_jwt_url }}"

  - name: Build and install libjwt
    shell: "autoreconf -i && ./configure && make install"
    args:
      chdir: "{{ build_dir }}/libjwt-{{ libjwt_version }}"
      creates: /usr/local/lib/libjwt.so.0

  - name: Build and install mod_authnz_jwt
    shell: "autoreconf -i && PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure && make install"
    args:
      chdir: "{{ build_dir }}/mod_authnz_jwt-{{ mod_authnz_jwt_version }}"
      creates: /usr/lib64/httpd/modules/mod_authnz_jwt.so

  - name: Create root for protected area
    file:
      path: "{{ httpd_protected_dir }}"
      state: directory

  - name: Put the main page into it
    copy:
      src: index.html
      dest: "{{ httpd_protected_dir }}"

  - name: Upload htpasswd file
    copy:
      src: htpasswd
      dest: "{{ httpd_passwd_file }}"

  - name: Upload username/password input form
    copy:
      src: get_token.html
      dest: /var/www/html

  - name: Generate JWT config
    template:
      src: jwt.conf.j2
      dest: /etc/httpd/conf.d/jwt.conf
      owner: apache
      mode: 0400
    register: jwt_cfg

  - name: Restart httpd
    service:
      name: httpd
      enabled: yes
      state: "{{ 'restarted' if jwt_cfg.changed else 'started' }}"
