- name: Install Vault server
  become: yes
  hosts: all
  vars:
    BinDir: /opt/bin
    ConsulConfig: /etc/consul.json
    ConsulDataDir: /opt/consul
  tasks:
  - name: Install required packages
    yum:
      name:
      - net-tools
      - unzip

  - name: Make required directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "{{ BinDir }}"
    - "{{ ConsulDataDir }}"

  - name: Download Consul and Vault
    unarchive:
      src: "https://releases.hashicorp.com/{{ item.key }}/{{ item.value }}/{{ item.key }}_{{ item.value }}_linux_amd64.zip"
      dest: "{{ BinDir }}"
      remote_src: yes
    with_dict:
      consul: 1.0.6
      vault: 0.10.0

  - name: Create Consul config
    template:
      src: "templates/{{ ConsulConfig | basename }}.j2"
      dest: "{{ ConsulConfig }}"
    register: consulCfg

  - name: Create Consul service
    template:
      src: templates/consul.service.j2
      dest: /usr/lib/systemd/system/consul.service
    register: consulSrv

  - name: Start Consul service
    systemd:
      name: consul
      daemon_reload: "{{ consulSrv.changed }}"
      enabled: yes
      state: "{{ 'restarted' if consulCfg.changed else 'started' }}"
