- name: Build OneOps
  become: yes
  hosts: all
  tasks:
  - name: Install packages
    yum:
      name:
      - gcc
      - gcc-c++
      - git
      - java-1.8.0-openjdk-devel
      - postgresql-devel
      - ruby-devel

  - name: Install ruby gems
    gem:
      name: "{{ item }}"
      user_install: no
    with_items:
    - bundler
    - graphviz

  - name: Clone repository
    git:
      dest: /home/vagrant/oneops
      repo: https://github.com/oneops/oneops.git
    become: no

  - name: Set environment
    blockinfile:
      path: /etc/environment
      block: |
        LANG=en_US.utf-8
        LC_ALL=en_US.utf-8
      create: yes
