Vagrant.configure(2) do |config|
	config.vm.box = 'centos/7'
	config.vm.hostname = 'rh7.griddynamics.net'
	config.vm.network :forwarded_port, guest: 80, host: 8080
	config.vm.network :private_network, ip: '192.168.168.7'
end
