Vagrant.configure(2) do |config|
	config.vm.box = 'centos/7'
  (1..3).each do |num|
    config.vm.define "cas#{num}" do |host|
    	host.vm.hostname = "cas-#{num}.griddynamics.net"
    	host.vm.network :private_network, ip: "192.168.168.1#{num}"
      if num == 3
      	host.vm.provision :ansible do |ansible|
          ansible.limit = 'all'
      		ansible.playbook = 'cassandra.yml'
          ansible.raw_arguments = ['-v']
      	end
      end
    end
  end
end
