Vagrant.configure(2) do |config|
	config.vm.box = 'centos/7'
	config.vm.hostname = 'cassandra.griddynamics.net'
	config.vm.network :private_network, ip: '192.168.168.7'
	config.vm.provision :ansible do |ansible|
		ansible.playbook = 'cassandra.yml'
	end
end
