- name: Install Apache Ranger
  become: yes
  hosts: all
  gather_facts: no
  vars:
    maven_version: 3.3.3
    maven_dir: "/usr/local/apache-maven-{{ maven_version }}"
    maven_tgz: /var/tmp/maven.tgz
    ranger_version: 1.2.0
    ranger_build_dir: "/var/tmp/apache-ranger-{{ ranger_version }}"
    ranger_dir: "/usr/local/ranger-{{ ranger_version }}-admin"
    ranger_target_dir: "{{ ranger_build_dir }}/target"
    ranger_tgz: /var/tmp/ranger.tgz
  tasks:
  - name: Install packages
    yum:
      name:
      - git
      - gcc
      - java-1.8.0-openjdk
      - mariadb-server
      - mysql-connector-java
      - net-tools

  - name: Start MySQL service
    service:
      name: mariadb
      enabled: yes
      state: started

  - name: Download Maven
    get_url:
      dest: "{{ maven_tgz }}"
      force: yes
      timeout: 600
      url: "https://archive.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"

  - name: Unpack Maven
    unarchive:
      dest: "{{ maven_dir | dirname }}"
      src: "{{ maven_tgz }}"
      remote_src: yes

  - name: Download Ranger sources
    get_url:
      dest: "{{ ranger_tgz }}"
      force: yes
      timeout: 600
      url: "http://apache-mirror.rbc.ru/pub/apache/ranger/{{ ranger_version }}/apache-ranger-{{ ranger_version }}.tar.gz"

  - name: Unpack Ranger sources
    unarchive:
      dest: "{{ ranger_build_dir | dirname }}"
      src: "{{ ranger_tgz }}"
      remote_src: yes

  - name: Build Ranger
    command: "mvn clean package assembly:assembly"
    args:
      chdir: "{{ ranger_build_dir }}"
      # the last artifact generated during the build
      creates: "{{ ranger_target_dir }}/ranger-{{ ranger_version }}-kylin-plugin.zip"
    environment:
      PATH: "{{ maven_dir }}/bin:/usr/bin:/bin"
      M2_HOME: "{{ maven_dir }}"
      MAVEN_OPTS: -Xmx512M

  - name: Unpack Ranger Admin
    unarchive:
      dest: "{{ ranger_dir | dirname }}"
      src: "{{ ranger_target_dir }}/ranger-{{ ranger_version }}-admin.tar.gz"
      remote_src: yes
